FROM openjdk:8
ADD ./target/currency-manager-service-0.0.1-SNAPSHOT.jar currency-manager-service-0.0.1-SNAPSHOT.jar
EXPOSE 8000
ENTRYPOINT ["java","-jar","currency-manager-service-0.0.1-SNAPSHOT.jar"]