FROM java:8-alpine
ADD target/user-authentication-service-0.0.1-SNAPSHOT.jar user-authentication-service-0.0.1-SNAPSHOT.jar
EXPOSE 8899
ENTRYPOINT ["java","-jar","user-authentication-service-0.0.1-SNAPSHOT.jar"]