INSERT INTO CURRENCY(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSOIN_FACTOR_VALUE,PORT)
VALUES(1,'USD','INR',65,0);

INSERT INTO CURRENCY(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSOIN_FACTOR_VALUE,PORT)
VALUES(2,'EUR','INR',75,0);

INSERT INTO CURRENCY(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSOIN_FACTOR_VALUE,PORT)
VALUES(3,'AUD','INR',25,0);