DROP TABLE IF EXISTS CURRENCY;
 
CREATE TABLE CURRENCY (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  CURRENCY_FROM VARCHAR(3) NOT NULL,
  CURRENCY_TO VARCHAR(3) NOT NULL,
  CONVERSOIN_FACTOR_VALUE DECIMAL(10,2) DEFAULT 0.00,
  PORT NUMBER
);